name: Generate & update the dashboard sites json file in the s3 folder specified in config.yml
on:
  push:
    branches:
      - main
      - staging

jobs:
  run-metadata-generator:
    runs-on: ubuntu-latest
  
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Configure AWS credentials from MAAP AWS Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute the metadata generator script
        env:
          STAGE: ${{ steps.extract_branch.outputs.branch }}
        run: python -m sites_generator.src.main
